on: push
jobs:
  generate-a-secret-output:
    runs-on: label1
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "this is testfile created from github actions" > /tmp/testfile
          echo "::add-mask::$the_secret"    
